const User = require('./models/user');

require('dotenv').config();
require('./config/database');

User.remove({})
.then(function() {
  return User.create([
    {
      "firstName": "Nick",
      "lastName": "Arocho",
      "email": "nick@boldlyfine.com",
      "password": "password",
      "isAdmin": true,
      "curStatement": "While I feel super old with this being a thing, I'm super excited to see everyone again.",
      "curHeadshot": "https://gravatar.com/avatar/e24f8bdb54f371c6ed2ca587bf90e08b?s=512&d=https://codepen.io/assets/avatars/user-avatar-512x512-6e240cf350d2f1cc07c2bed234c3a3bb5f1b237023c204c782622e80d6b212ba.png",
      "curLocation": "Los Angeles, CA",
      "curJobs": ["Web Developer", "Drummer", "Business Owner"],
      "curMaritalStatus": "Married",
      "curKids": false,
      "curNumKids": 0,
      "elapStatement": "Lots of travel. Lots of love. Lots of learning.",
      "elapPhotos": ["https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png"],
      "elapLocations": ["Phoenix, AZ", "Newport Beach, CA", "Osaka, Japan"],
      "elapJobs": ["Freelance Drummer", "Disneyland Parade Performer", "Server"],
      "elapEducation": ["Arizona State University", "General Assembly"],
      "elapTravel": ["Japan", "Switzerland", "England", "France", "Italy", "Netherlands", "Belgium", "South Korea", "Mexico", "Lithuania", "Taiwan", "Fiji", "Spain"],
      "elapMilestones": [{"title": "DCI World Championship", "year": 2010, "description": "Blue Devils Drum and Bugle Corps"}, {"title": "Got Married", "year": 2017, "description": "I am a lucky man."}],
      "initStatement": "I think it's so weird when people say they hated high school, because it was a blast for me.",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": ["https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png"],
      "initTeams": ["Drumline", "Jazz Band", "Concert Band", "Marching Band", "Baseball", "Football", "Track"],
      "memories": [{"title": "Halftime IS Gametime", "description": "Playing on the track during the varsity football games were always such a blast."}]
    },
    {
      "firstName": "John",
      "lastName": "Tttttt",
      "email": "t@t.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "Joe",
      "lastName": "Shmoe",
      "email": "joe@shmoe.com",
      "password": "password",
      "isAdmin": false,
      "curStatement": "I am Joe Shmoe. Just a regular guy.",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "Phoenix, AZ",
      "curJobs": ["Freelance Knitter", "Tiger Wrangler"],
      "curMaritalStatus": "Divorced",
      "curKids": true,
      "curNumKids": 7,
      "elapStatement": "I had lots of kids. That took up most of my time.",
      "elapPhotos": ["https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png"],
      "elapLocations": ["Detroit, MI", "Pheonix, AZ", "Mexico City, Mexico"],
      "elapJobs": ["Uber Driver", "Speech Pathologist"],
      "elapEducation": ["MIT"],
      "elapTravel": ["United States of America, Canada, Mexico"],
      "elapMilestones": [{"title": "First Kid", "year": 2008, "description": "Little Johnny Shmoe. Proud papa."}, {"title": "Second Kid", "year": 2009, "description": "Jane Shmoe, my little princess."}],
      "initStatement": "High school was whatever, I guess.",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": ["https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png", "https://i.imgur.com/50rRlbU.png"],
      "initTeams": ["Mathletes", "STUGO", "Badminton"],
      "memories": [{"title": "My Senior Prank", "description": "Haha, one time I swapped out my teacher's blue pen for a black pen. That was crazy..."}]
    },
    {
      "firstName": "John",
      "lastName": "Aaaaaa",
      "email": "a@a.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Cccccc",
      "email": "c@c.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Dddddd",
      "email": "d@d.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Eeeeee",
      "email": "e@e.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Ffffff",
      "email": "f@f.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Gggggg",
      "email": "g@g.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Hhhhhh",
      "email": "h@h.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Bbbbbb",
      "email": "b@b.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Iiiiii",
      "email": "i@i.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Jjjjjj",
      "email": "j@j.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Kkkkkk",
      "email": "k@k.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Llllll",
      "email": "l@l.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Mmmmmm",
      "email": "m@m.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Nnnnnn",
      "email": "n@n.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Oooooo",
      "email": "o@o.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Pppppp",
      "email": "p@p.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Rrrrrr",
      "email": "r@r.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Ssssss",
      "email": "s@s.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Yyyyyy",
      "email": "y@y.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Uuuuuu",
      "email": "u@u.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Vvvvvv",
      "email": "v@v.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Wwwwww",
      "email": "w@w.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Xxxxxx",
      "email": "x@x.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    },
    {
      "firstName": "John",
      "lastName": "Zzzzzz",
      "email": "z@z.com",
      "password": "",
      "isAdmin": null,
      "curStatement": "",
      "curHeadshot": "https://i.imgur.com/50rRlbU.png",
      "curLocation": "",
      "curJobs": [],
      "curMaritalStatus": "",
      "curKids": null,
      "curNumKids": null,
      "elapStatement": "",
      "elapPhotos": [],
      "elapLocations": [],
      "elapJobs": [],
      "elapEducation": [],
      "elapTravel": [],
      "elapMilestones": [],
      "initStatement": "",
      "initHeadshot": "https://i.imgur.com/taZ0IA0.png",
      "initPhotos": [],
      "initTeams": [],
      "memories": []
    }
  ])
})
.then(function(users) {
  console.log(users);
  process.exit();
})